version: "3.9"
services:
  web:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./dev/nginx/nginx.conf:/etc/nginx/conf.d/nginx.conf
      - ./app:/app
  php:
    image: php:fpm
    volumes:
      - ./app:/app
